//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuLich.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinhLuan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BinhLuan()
        {
            this.BinhLuan1 = new HashSet<BinhLuan>();
        }
    
        public int MaBinhLuan { get; set; }
        public int MaTour { get; set; }
        public string MaTaiKhoan { get; set; }
        public Nullable<int> LuotThich { get; set; }
        public Nullable<int> LuotTraLoi { get; set; }
        public Nullable<int> LuotChiaSe { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> idReply { get; set; }
        public Nullable<int> Cap { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public Nullable<int> TinhTrang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuan1 { get; set; }
        public virtual BinhLuan BinhLuan2 { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
        public virtual TourDuLich TourDuLich { get; set; }
    }
}
