//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuLich.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CamNangDuLich
    {
        public int ID_CamNang { get; set; }
        public string TieuDe { get; set; }
        public string TomTat { get; set; }
        public string HinhAnh { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayViet { get; set; }
        public Nullable<bool> HienTrangChu { get; set; }
    }
}
