//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuLich.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatTourDetail
    {
        public int idTour { get; set; }
        public int idDatTour { get; set; }
        public Nullable<double> Gia { get; set; }
        public string TinhTrang { get; set; }
        public string GhiChu { get; set; }
    
        public virtual TourDuLich TourDuLich { get; set; }
        public virtual DatTour DatTour { get; set; }
    }
}
