//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuLich.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HinhAnh
    {
        public int ID_HinhAnh { get; set; }
        public int idAlbum { get; set; }
        public string Url { get; set; }
        public string TieuDe { get; set; }
        public Nullable<int> ThuTu { get; set; }
    
        public virtual AlbumAnh AlbumAnh { get; set; }
    }
}
