//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuLich.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachSan
    {
        public int ID_KhachSan { get; set; }
        public string TenKhachSan { get; set; }
        public Nullable<double> GiaPhong { get; set; }
        public string ViTri { get; set; }
        public Nullable<int> IdTinh { get; set; }
        public Nullable<int> IdMucGia { get; set; }
        public string HinhAnh { get; set; }
        public string BaiViet { get; set; }
    
        public virtual TinhThanh TinhThanh { get; set; }
    }
}
