//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuLich.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KieuTour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KieuTour()
        {
            this.Tour_KieuTour = new HashSet<Tour_KieuTour>();
        }
    
        public int ID_KieuTour { get; set; }
        public string TenKieuTour { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tour_KieuTour> Tour_KieuTour { get; set; }
    }
}
