//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuLich.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DuLichDBEntities : DbContext
    {
        public DuLichDBEntities()
            : base("name=DuLichDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AlbumAnh> AlbumAnhs { get; set; }
        public virtual DbSet<CamNangDuLich> CamNangDuLiches { get; set; }
        public virtual DbSet<Gia> Gias { get; set; }
        public virtual DbSet<HinhAnh> HinhAnhs { get; set; }
        public virtual DbSet<KieuTour> KieuTours { get; set; }
        public virtual DbSet<LoaiTour> LoaiTours { get; set; }
        public virtual DbSet<Slider> Sliders { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<Tour_KieuTour> Tour_KieuTour { get; set; }
        public virtual DbSet<ChucNang> ChucNangs { get; set; }
        public virtual DbSet<PhanQuyen> PhanQuyens { get; set; }
        public virtual DbSet<KhachSan> KhachSans { get; set; }
        public virtual DbSet<TinhThanh> TinhThanhs { get; set; }
        public virtual DbSet<LichTrinh> LichTrinhs { get; set; }
        public virtual DbSet<DichVu> DichVus { get; set; }
        public virtual DbSet<DatTourDetail> DatTourDetails { get; set; }
        public virtual DbSet<PhuongTien> PhuongTiens { get; set; }
        public virtual DbSet<TourDuLich> TourDuLiches { get; set; }
        public virtual DbSet<TinTuc> TinTucs { get; set; }
        public virtual DbSet<DatTour> DatTours { get; set; }
        public virtual DbSet<BinhLuan> BinhLuans { get; set; }
    
        public virtual ObjectResult<spTimkiemTour_Result> spTimkiemTour(Nullable<int> idTinh, Nullable<int> idLoaiTour, Nullable<int> idMucGia)
        {
            var idTinhParameter = idTinh.HasValue ?
                new ObjectParameter("idTinh", idTinh) :
                new ObjectParameter("idTinh", typeof(int));
    
            var idLoaiTourParameter = idLoaiTour.HasValue ?
                new ObjectParameter("idLoaiTour", idLoaiTour) :
                new ObjectParameter("idLoaiTour", typeof(int));
    
            var idMucGiaParameter = idMucGia.HasValue ?
                new ObjectParameter("idMucGia", idMucGia) :
                new ObjectParameter("idMucGia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spTimkiemTour_Result>("spTimkiemTour", idTinhParameter, idLoaiTourParameter, idMucGiaParameter);
        }
    
        public virtual ObjectResult<spTimKiemKhachSan_Result> spTimKiemKhachSan(Nullable<int> idTinh, Nullable<int> idMucGia)
        {
            var idTinhParameter = idTinh.HasValue ?
                new ObjectParameter("idTinh", idTinh) :
                new ObjectParameter("idTinh", typeof(int));
    
            var idMucGiaParameter = idMucGia.HasValue ?
                new ObjectParameter("idMucGia", idMucGia) :
                new ObjectParameter("idMucGia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spTimKiemKhachSan_Result>("spTimKiemKhachSan", idTinhParameter, idMucGiaParameter);
        }
    }
}
