//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuLich.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhuongTien
    {
        public int ID { get; set; }
        public string Ten { get; set; }
        public string Loại { get; set; }
        public Nullable<int> Gia { get; set; }
        public string DonVi { get; set; }
        public string PhuongTien1 { get; set; }
    }
}
