//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuLich.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourDuLich
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TourDuLich()
        {
            this.DatTourDetails = new HashSet<DatTourDetail>();
            this.Sliders = new HashSet<Slider>();
            this.Tour_KieuTour = new HashSet<Tour_KieuTour>();
            this.DichVus = new HashSet<DichVu>();
        }
    
        public int ID { get; set; }
        public string TieuDe { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<double> SoNgayDiTour { get; set; }
        public string LichDinhKy { get; set; }
        public string DiaDiem { get; set; }
        public Nullable<int> SoNguoiToiDa { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public string GioKhoiHanh { get; set; }
        public string DiChuyen { get; set; }
        public string DiemXuatPhat { get; set; }
        public Nullable<double> GiaTour { get; set; }
        public Nullable<int> LuotXem { get; set; }
        public Nullable<double> DanhGia { get; set; }
        public string BaiViet { get; set; }
        public Nullable<int> IdTinh { get; set; }
        public Nullable<int> IdLoaiTour { get; set; }
        public Nullable<int> IdMucGia { get; set; }
        public Nullable<int> IdAlbum { get; set; }
        public Nullable<int> IdLichTrinh { get; set; }
    
        public virtual AlbumAnh AlbumAnh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatTourDetail> DatTourDetails { get; set; }
        public virtual Gia Gia { get; set; }
        public virtual LichTrinh LichTrinh { get; set; }
        public virtual LoaiTour LoaiTour { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Slider> Sliders { get; set; }
        public virtual TinhThanh TinhThanh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tour_KieuTour> Tour_KieuTour { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DichVu> DichVus { get; set; }
    }
}
